### ISSUE TITLE
cygger status and alternative

### ISSUE THREAD

**Issue by haggen** [RamirezAlex/cygger#4]
Hi there,

I see that the last update was over a year ago which suggests its soft deprecation, so I'd like to ask if you have outgrown this solution or if you're using an alternative?

Thanks in advance.

**Comment by RamirezAlex** [comment]
Thanks @haggen,

In my projects I am not using it, because I do more GraphQL than REST recently. I haven't done really much updating it, because I have not seen much interest in this tool. However, if you are interested in using it or even better contributing, I can put some effort on this.

The alternative for now that I know is to write the API tests using Cypress directly. 
You can follow examples in: https://github.com/cypress-io/cypress-realworld-app/tree/develop/cypress/tests/api

**Comment by haggen** [comment]
@RamirezAlex  Thank you for the quick reply! 🍻

Not interested in this particular solution, I was just researching my options. The idea behind this project popped in my head but I guess there are better ways to approach this.

Thanks again and have a good one!
